config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
  # mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minumum: 3, maximum: 15}

  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  before_action :require_user, only: [:index]

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      # redirect_to root_path
      ActionCable.server.broadcast "chatroom_channel", {msg: message_render(message)}
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render partial: 'message', locals: {message: message}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged successfully!"
      redirect_to root_path
    else
      flash.now[:alert] = "There was something wrong with your login"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end

  private
  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular inverted purple wechat icon"></i>
  Say something
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="messages-container">
          <% @messages.each do |message| %>
            <%= render message %>
          <% end %>
        </div>
      </div>
      <div class="extra content">
        <%= form_with(model: @message, url: message_path, remote:true, class: "ui reply form") do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Write something" %>
              <%= f.button '<i class="bordered inverted purple edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">Home</a>
          <a class="item">Messages</a>
          <a class="item">Friends</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<div>
  <% flash.each do |name, msg| %>
    <div class="ui <%= name == "notice" ? "positive" : "negative" %> message">
      <i class="close icon"></i>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui large inverted menu">
  <div class="ui container">
      <a class="item">
        Chatroom
      </a>
      <a class="item">
        Messages
      </a>
      <div class="right menu">
        <div class="ui dropdown item">
          Account <i class="dropdown icon"></i>
          <div class="menu">
            <%if logged_in?%>
              <%= link_to "Log out", logout_path, data: {turbo_method: :delete}, class: "item" %>
            <%else%>
              <%= link_to "Login", login_path, {:class => "item"} %>
              <a class="item">Sign up</a>
            <%end%>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/flashes'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>